// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFmmAgc5ALg3CQG4u3WwSjSJTcoE_C6h8',
    appId: '1:1063588914429:web:830f8877367a55751a8a94',
    messagingSenderId: '1063588914429',
    projectId: 'seniorsync-4dca0',
    authDomain: 'seniorsync-4dca0.firebaseapp.com',
    storageBucket: 'seniorsync-4dca0.firebasestorage.app',
    measurementId: 'G-S9TBYMP1CV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3nAq4UZcew6z5lwLBvtPaVs-8ZFopmYc',
    appId: '1:1063588914429:android:209cfdfafd204c8b1a8a94',
    messagingSenderId: '1063588914429',
    projectId: 'seniorsync-4dca0',
    storageBucket: 'seniorsync-4dca0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgYk764v4xS-5SEnY6pYX85-8dEiXfzy8',
    appId: '1:1063588914429:ios:58997cda5992f3481a8a94',
    messagingSenderId: '1063588914429',
    projectId: 'seniorsync-4dca0',
    storageBucket: 'seniorsync-4dca0.firebasestorage.app',
    iosBundleId: 'com.example.seniorsync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgYk764v4xS-5SEnY6pYX85-8dEiXfzy8',
    appId: '1:1063588914429:ios:58997cda5992f3481a8a94',
    messagingSenderId: '1063588914429',
    projectId: 'seniorsync-4dca0',
    storageBucket: 'seniorsync-4dca0.firebasestorage.app',
    iosBundleId: 'com.example.seniorsync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFmmAgc5ALg3CQG4u3WwSjSJTcoE_C6h8',
    appId: '1:1063588914429:web:c826a84e86175a5e1a8a94',
    messagingSenderId: '1063588914429',
    projectId: 'seniorsync-4dca0',
    authDomain: 'seniorsync-4dca0.firebaseapp.com',
    storageBucket: 'seniorsync-4dca0.firebasestorage.app',
    measurementId: 'G-Z40K2SJ71F',
  );
}
